@AspNetCoreEcommerce_HostAddress = http://localhost:5209

POST {{AspNetCoreEcommerce_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "user2@gmail.com",
  "password": "password",
  "confirmPassword": "password",
  "firstName": "First",
  "lastName": "Last",
  "phoneNumber": "0987654321123"
}
###
POST {{AspNetCoreEcommerce_HostAddress}}/api/auth/confirm-email
Content-Type: application/json

{
  "email": "user2@gmail.com",
  "token": "CfDJ8PZh6n2IbQpBidiE+PfU6rHZpLnLcScNHzRRTL5ZmUOuXTqmCk+K7gGtPnfuZ90jb6RnQZy/Ot4d9KNxdMFMa81j3H1gH1htYP4HxyoTeA3/gZ98C4XfeBRIorJoSZNGP2sYBqtjSQKl5DXyNSMqFDjH7L7OX5tJ36HLn8mFtfOeWIHoHOfORb5Z+1cvEHaxL6UddMuA653P1Yx6wz4RoUtAv/Iv79cCghjCDMiSTToX+l/TnJygNLjQ+UZiWOrpKg=="
}
###
POST {{AspNetCoreEcommerce_HostAddress}}/api/auth/login
Content-Type: application/json

{
    "Email": "user2@gmail.com",
    "password": "password"
}

###
GET {{AspNetCoreEcommerce_HostAddress}}/api/auth/profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJBc3BOZXRDb3JlV2ViQXBpIiwiaXNzIjoiQXNwTmV0Q29yZVdlYkFwaSIsImV4cCI6MTc0NjE3ODE4NSwic3ViIjoiMDE5NjkwMTktM2M3Ni03Y2ZjLWJkNTQtNTE0OGUxNjNmODVjIiwiZW1haWwiOiJ1c2VyMkBnbWFpbC5jb20iLCJpYXQiOjE3NDYxNzQ1ODUsIm5iZiI6MTc0NjE3NDU4NX0.Az3IMM31fxXkv2wr7LWLtk6FRWoxtfVjLnwCShlIHc4

###
GET {{AspNetCoreEcommerce_HostAddress}}/api/auth/get-user-role/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJBc3BOZXRDb3JlV2ViQXBpIiwiaXNzIjoiQXNwTmV0Q29yZVdlYkFwaSIsImV4cCI6MTc0NjE3ODE4NSwic3ViIjoiMDE5NjkwMTktM2M3Ni03Y2ZjLWJkNTQtNTE0OGUxNjNmODVjIiwiZW1haWwiOiJ1c2VyMkBnbWFpbC5jb20iLCJpYXQiOjE3NDYxNzQ1ODUsIm5iZiI6MTc0NjE3NDU4NX0.Az3IMM31fxXkv2wr7LWLtk6FRWoxtfVjLnwCShlIHc4

###
GET {{AspNetCoreEcommerce_HostAddress}}/api/product/
###

GET {{AspNetCoreEcommerce_HostAddress}}/api/product/01951487-ed0b-72ac-b7f1-a562259107c8/
###

POST {{AspNetCoreEcommerce_HostAddress}}/api/cart/add/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJDdXN0b21lciIsImlzcyI6IkFzcE5ldENvcmVXZWJBcGkiLCJleHAiOjE3NDE2MzE0MTAsInN1YiI6IjAxOTU4MTE1LWFmN2EtNzJiMy1iNDE3LTJhMmYxOTliMDg5MyIsImVtYWlsIjoiYW1hZWNoaWp1ZGUxNzhAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQ3VzdG9tZXIiLCJpYXQiOjE3NDE2Mjc4MTAsIm5iZiI6MTc0MTYyNzgxMH0.fEV7wgm42nKcxD7KDJo7j__GXKKwG8jl11a6_KBUMtQ

{
  "productId": "01951487-ed0b-72ac-b7f1-a562259107c8",
  "quantity": 5
}


###
GET {{AspNetCoreEcommerce_HostAddress}}/api/cart/view/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJDdXN0b21lciIsImlzcyI6IkFzcE5ldENvcmVXZWJBcGkiLCJleHAiOjE3NDE2MzE0MTAsInN1YiI6IjAxOTU4MTE1LWFmN2EtNzJiMy1iNDE3LTJhMmYxOTliMDg5MyIsImVtYWlsIjoiYW1hZWNoaWp1ZGUxNzhAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQ3VzdG9tZXIiLCJpYXQiOjE3NDE2Mjc4MTAsIm5iZiI6MTc0MTYyNzgxMH0.fEV7wgm42nKcxD7KDJo7j__GXKKwG8jl11a6_KBUMtQ

###

POST {{AspNetCoreEcommerce_HostAddress}}/api/cart/add/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJDdXN0b21lciIsImlzcyI6IkFzcE5ldENvcmVXZWJBcGkiLCJleHAiOjE3NDE2MzE0MTAsInN1YiI6IjAxOTU4MTE1LWFmN2EtNzJiMy1iNDE3LTJhMmYxOTliMDg5MyIsImVtYWlsIjoiYW1hZWNoaWp1ZGUxNzhAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQ3VzdG9tZXIiLCJpYXQiOjE3NDE2Mjc4MTAsIm5iZiI6MTc0MTYyNzgxMH0.fEV7wgm42nKcxD7KDJo7j__GXKKwG8jl11a6_KBUMtQ

{
  "productId": "97951466-ed0b-72ac-b7f1-a562259107c8",
  "quantity": 7
}
###
DELETE {{AspNetCoreEcommerce_HostAddress}}/api/cart/remove/97951466-ed0b-72ac-b7f1-a562259107c8/
Content-Type: /application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJDdXN0b21lciIsImlzcyI6IkFzcE5ldENvcmVXZWJBcGkiLCJleHAiOjE3NDE2MzE0MTAsInN1YiI6IjAxOTU4MTE1LWFmN2EtNzJiMy1iNDE3LTJhMmYxOTliMDg5MyIsImVtYWlsIjoiYW1hZWNoaWp1ZGUxNzhAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQ3VzdG9tZXIiLCJpYXQiOjE3NDE2Mjc4MTAsIm5iZiI6MTc0MTYyNzgxMH0.fEV7wgm42nKcxD7KDJo7j__GXKKwG8jl11a6_KBUMtQ

###
POST {{AspNetCoreEcommerce_HostAddress}}/api/shippingaddress/add/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJDdXN0b21lciIsImlzcyI6IkFzcE5ldENvcmVXZWJBcGkiLCJleHAiOjE3NDE2MzE0MTAsInN1YiI6IjAxOTU4MTE1LWFmN2EtNzJiMy1iNDE3LTJhMmYxOTliMDg5MyIsImVtYWlsIjoiYW1hZWNoaWp1ZGUxNzhAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQ3VzdG9tZXIiLCJpYXQiOjE3NDE2Mjc4MTAsIm5iZiI6MTc0MTYyNzgxMH0.fEV7wgm42nKcxD7KDJo7j__GXKKwG8jl11a6_KBUMtQ

{
  "firstName": "Amaechi",
  "lastName": "Jude",
  "phone": "0987654321",
  "addressOne": "Ajah",
  "secondAddress": "Lagos",
  "city": "Lagos",
  "state": "Lagos",
  "country": "Nigeria",
  "postalCode": "243891"
}
###
GET  {{AspNetCoreEcommerce_HostAddress}}/api/shippingaddress/view/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJDdXN0b21lciIsImlzcyI6IkFzcE5ldENvcmVXZWJBcGkiLCJleHAiOjE3NDE2MzE0MTAsInN1YiI6IjAxOTU4MTE1LWFmN2EtNzJiMy1iNDE3LTJhMmYxOTliMDg5MyIsImVtYWlsIjoiYW1hZWNoaWp1ZGUxNzhAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQ3VzdG9tZXIiLCJpYXQiOjE3NDE2Mjc4MTAsIm5iZiI6MTc0MTYyNzgxMH0.fEV7wgm42nKcxD7KDJo7j__GXKKwG8jl11a6_KBUMtQ


###
POST {{AspNetCoreEcommerce_HostAddress}}/api/order/create/01958120-519d-7b64-88a0-b0995057938d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJDdXN0b21lciIsImlzcyI6IkFzcE5ldENvcmVXZWJBcGkiLCJleHAiOjE3NDE2MzE0MTAsInN1YiI6IjAxOTU4MTE1LWFmN2EtNzJiMy1iNDE3LTJhMmYxOTliMDg5MyIsImVtYWlsIjoiYW1hZWNoaWp1ZGUxNzhAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQ3VzdG9tZXIiLCJpYXQiOjE3NDE2Mjc4MTAsIm5iZiI6MTc0MTYyNzgxMH0.fEV7wgm42nKcxD7KDJo7j__GXKKwG8jl11a6_KBUMtQ

###

GET  {{AspNetCoreEcommerce_HostAddress}}/api/order/all/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJDdXN0b21lciIsImlzcyI6IkFzcE5ldENvcmVXZWJBcGkiLCJleHAiOjE3NDE2MzE0MTAsInN1YiI6IjAxOTU4MTE1LWFmN2EtNzJiMy1iNDE3LTJhMmYxOTliMDg5MyIsImVtYWlsIjoiYW1hZWNoaWp1ZGUxNzhAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQ3VzdG9tZXIiLCJpYXQiOjE3NDE2Mjc4MTAsIm5iZiI6MTc0MTYyNzgxMH0.fEV7wgm42nKcxD7KDJo7j__GXKKwG8jl11a6_KBUMtQ

###


POST {{AspNetCoreEcommerce_HostAddress}}/api/payment/initiate/01958131-4c0b-75ad-a52b-3dad9ae41a47/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJDdXN0b21lciIsImlzcyI6IkFzcE5ldENvcmVXZWJBcGkiLCJleHAiOjE3NDE2MzE0MTAsInN1YiI6IjAxOTU4MTE1LWFmN2EtNzJiMy1iNDE3LTJhMmYxOTliMDg5MyIsImVtYWlsIjoiYW1hZWNoaWp1ZGUxNzhAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQ3VzdG9tZXIiLCJpYXQiOjE3NDE2Mjc4MTAsIm5iZiI6MTc0MTYyNzgxMH0.fEV7wgm42nKcxD7KDJo7j__GXKKwG8jl11a6_KBUMtQ

###