@AspNetCoreEcommerce_HostAddress = http://localhost:5209

POST {{AspNetCoreEcommerce_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password": "password",
  "confirmPassword": "password",
  "firstName": "First",
  "lastName": "Last",
  "phoneNumber": "0987654321123"
}
###
POST {{AspNetCoreEcommerce_HostAddress}}/api/auth/confirm-email
Content-Type: application/json

{
  "email": "user@gmail.com",
  "token": "CfDJ8PZh6n2IbQpBidiE%2BPfU6rFCtHa203hq%2Fn3cWpyzff%2Fh1wLv4b1wpFeA4lMIsuhXdtulVyE1zWGlHSRlqZGpTYNKeHitL0J9tfJqbWSUXgAAYTTOncpalpl6mGKv0GOaSbK1CdWbgw71KCyR7Pqa7Ye8ETrjYnXnKtLn56iLwhWLxbx80K%2F%2BN4NaRkDwsUQf3hdc9ZyrZ6szwdsgQHKkkV%2BzXvddiP7ZMBYrTGxc4OWqt2aFHh44P0DR2VzoooKmag%3D%3D"
}
###
POST {{AspNetCoreEcommerce_HostAddress}}/api/auth/login
Content-Type: application/json

{
    "Email": "user@gmail.com",
    "password": "password"
}

###
GET {{AspNetCoreEcommerce_HostAddress}}/api/auth/profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJBc3BOZXRDb3JlV2ViQXBpIiwiaXNzIjoiQXNwTmV0Q29yZVdlYkFwaSIsImV4cCI6MTc0NzAwMDg1OSwic3ViIjoiMDE5NmI0ZDItNzMyZS03NjVlLWJlMzYtNjE1NDVkNzc2ODI5IiwiZW1haWwiOiJ1c2VyQGdtYWlsLmNvbSIsImlhdCI6MTc0NjgyODA1OSwibmJmIjoxNzQ2ODI4MDU5fQ.Tqgl6TXUM6YYbs100JXkKM6nK91wIw0S3INwQgYPwYE

###
GET {{AspNetCoreEcommerce_HostAddress}}/api/auth/get-user-role/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJBc3BOZXRDb3JlV2ViQXBpIiwiaXNzIjoiQXNwTmV0Q29yZVdlYkFwaSIsImV4cCI6MTc0NjE3ODE4NSwic3ViIjoiMDE5NjkwMTktM2M3Ni03Y2ZjLWJkNTQtNTE0OGUxNjNmODVjIiwiZW1haWwiOiJ1c2VyMkBnbWFpbC5jb20iLCJpYXQiOjE3NDYxNzQ1ODUsIm5iZiI6MTc0NjE3NDU4NX0.Az3IMM31fxXkv2wr7LWLtk6FRWoxtfVjLnwCShlIHc4

###
GET {{AspNetCoreEcommerce_HostAddress}}/api/product/
###

GET {{AspNetCoreEcommerce_HostAddress}}/api/product/0196a187-f7ba-7527-aea7-3b884db4168e/
###

POST {{AspNetCoreEcommerce_HostAddress}}/api/cart/add/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJBc3BOZXRDb3JlV2ViQXBpIiwiaXNzIjoiQXNwTmV0Q29yZVdlYkFwaSIsImV4cCI6MTc0NjgyNzA4Nywic3ViIjoiMDE5NmI0ZDItNzMyZS03NjVlLWJlMzYtNjE1NDVkNzc2ODI5IiwiZW1haWwiOiJ1c2VyQGdtYWlsLmNvbSIsImlhdCI6MTc0NjgyMzQ4NywibmJmIjoxNzQ2ODIzNDg3fQ.SFoV-YeEBlW33XxUZtjXXH4YiXGuKyoVwxlTUGqdZCw

{
  "productId": "0196a187-f7ba-7527-aea7-3b884db4168e",
  "quantity": 5
}


###
GET {{AspNetCoreEcommerce_HostAddress}}/api/cart/view/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJBc3BOZXRDb3JlV2ViQXBpIiwiaXNzIjoiQXNwTmV0Q29yZVdlYkFwaSIsImV4cCI6MTc0NzE3MjI5NCwic3ViIjoiMDE5NmI0ZDItNzMyZS03NjVlLWJlMzYtNjE1NDVkNzc2ODI5IiwiZW1haWwiOiJ1c2VyQGdtYWlsLmNvbSIsImlhdCI6MTc0Njk5OTQ5NCwibmJmIjoxNzQ2OTk5NDk0fQ.L_LEpMQdbY1NWYQN9148RZpRl9nl_ZQafYFmCTWLOyM
###

POST {{AspNetCoreEcommerce_HostAddress}}/api/cart/add/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJBc3BOZXRDb3JlV2ViQXBpIiwiaXNzIjoiQXNwTmV0Q29yZVdlYkFwaSIsImV4cCI6MTc0NzE3MjI5NCwic3ViIjoiMDE5NmI0ZDItNzMyZS03NjVlLWJlMzYtNjE1NDVkNzc2ODI5IiwiZW1haWwiOiJ1c2VyQGdtYWlsLmNvbSIsImlhdCI6MTc0Njk5OTQ5NCwibmJmIjoxNzQ2OTk5NDk0fQ.L_LEpMQdbY1NWYQN9148RZpRl9nl_ZQafYFmCTWLOyM

{
  "productId": "0196a187-f7bb-7f78-aecd-4c1e30f81cb3",
  "quantity": 7
}
###
DELETE {{AspNetCoreEcommerce_HostAddress}}/api/cart/remove/0196a187-f7ba-7527-aea7-3b884db4168e
Content-Type: /application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJBc3BOZXRDb3JlV2ViQXBpIiwiaXNzIjoiQXNwTmV0Q29yZVdlYkFwaSIsImV4cCI6MTc0NzE3MjI5NCwic3ViIjoiMDE5NmI0ZDItNzMyZS03NjVlLWJlMzYtNjE1NDVkNzc2ODI5IiwiZW1haWwiOiJ1c2VyQGdtYWlsLmNvbSIsImlhdCI6MTc0Njk5OTQ5NCwibmJmIjoxNzQ2OTk5NDk0fQ.L_LEpMQdbY1NWYQN9148RZpRl9nl_ZQafYFmCTWLOyM
###
POST {{AspNetCoreEcommerce_HostAddress}}/api/shippingaddress/add/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJBc3BOZXRDb3JlV2ViQXBpIiwiaXNzIjoiQXNwTmV0Q29yZVdlYkFwaSIsImV4cCI6MTc0Njc5NzMyMywic3ViIjoiMDE5NmI0ZDItNzMyZS03NjVlLWJlMzYtNjE1NDVkNzc2ODI5IiwiZW1haWwiOiJ1c2VyQGdtYWlsLmNvbSIsImlhdCI6MTc0Njc5MzcyMywibmJmIjoxNzQ2NzkzNzIzfQ.OTyAM2RrXzUYMieGKpkUAg-xwSbJVKXDb_yJ1L8E0DA

{
  "firstName": "Amaechi",
  "lastName": "Jude",
  "phone": "0987654321",
  "addressLine1": "Ajah",
  "addressLine2": "Lagos",
  "city": "Lagos",
  "state": "Lagos",
  "country": "Nigeria",
  "postalCode": "243891"
}
###
GET  {{AspNetCoreEcommerce_HostAddress}}/api/shippingaddress/view/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJDdXN0b21lciIsImlzcyI6IkFzcE5ldENvcmVXZWJBcGkiLCJleHAiOjE3NDE2MzE0MTAsInN1YiI6IjAxOTU4MTE1LWFmN2EtNzJiMy1iNDE3LTJhMmYxOTliMDg5MyIsImVtYWlsIjoiYW1hZWNoaWp1ZGUxNzhAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQ3VzdG9tZXIiLCJpYXQiOjE3NDE2Mjc4MTAsIm5iZiI6MTc0MTYyNzgxMH0.fEV7wgm42nKcxD7KDJo7j__GXKKwG8jl11a6_KBUMtQ


###
POST {{AspNetCoreEcommerce_HostAddress}}/api/order/create/01958120-519d-7b64-88a0-b0995057938d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJDdXN0b21lciIsImlzcyI6IkFzcE5ldENvcmVXZWJBcGkiLCJleHAiOjE3NDE2MzE0MTAsInN1YiI6IjAxOTU4MTE1LWFmN2EtNzJiMy1iNDE3LTJhMmYxOTliMDg5MyIsImVtYWlsIjoiYW1hZWNoaWp1ZGUxNzhAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQ3VzdG9tZXIiLCJpYXQiOjE3NDE2Mjc4MTAsIm5iZiI6MTc0MTYyNzgxMH0.fEV7wgm42nKcxD7KDJo7j__GXKKwG8jl11a6_KBUMtQ

###

GET  {{AspNetCoreEcommerce_HostAddress}}/api/order/all/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJDdXN0b21lciIsImlzcyI6IkFzcE5ldENvcmVXZWJBcGkiLCJleHAiOjE3NDE2MzE0MTAsInN1YiI6IjAxOTU4MTE1LWFmN2EtNzJiMy1iNDE3LTJhMmYxOTliMDg5MyIsImVtYWlsIjoiYW1hZWNoaWp1ZGUxNzhAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQ3VzdG9tZXIiLCJpYXQiOjE3NDE2Mjc4MTAsIm5iZiI6MTc0MTYyNzgxMH0.fEV7wgm42nKcxD7KDJo7j__GXKKwG8jl11a6_KBUMtQ

###


POST {{AspNetCoreEcommerce_HostAddress}}/api/payment/initiate/01958131-4c0b-75ad-a52b-3dad9ae41a47/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJDdXN0b21lciIsImlzcyI6IkFzcE5ldENvcmVXZWJBcGkiLCJleHAiOjE3NDE2MzE0MTAsInN1YiI6IjAxOTU4MTE1LWFmN2EtNzJiMy1iNDE3LTJhMmYxOTliMDg5MyIsImVtYWlsIjoiYW1hZWNoaWp1ZGUxNzhAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQ3VzdG9tZXIiLCJpYXQiOjE3NDE2Mjc4MTAsIm5iZiI6MTc0MTYyNzgxMH0.fEV7wgm42nKcxD7KDJo7j__GXKKwG8jl11a6_KBUMtQ

###