@AspNetCoreEcommerce_HostAddress = http://localhost:5209

POST {{AspNetCoreEcommerce_HostAddress}}/api/customer/register
Content-Type: application/json

{
    "customerEmail": "userone@email.com",
    "password": "password",
    "firstName": "Amaechi",
    "lastName": "Jude",
    "CustomerPhone": "09122999887709"
}

###
POST {{AspNetCoreEcommerce_HostAddress}}/api/customer/login
Content-Type: application/json

{
    "Email": "userone@email.com",
    "password": "password"
}

###

POST {{AspNetCoreEcommerce_HostAddress}}/api/vendor/login
Content-Type: application/json

{
  "email": "scalar@email.com",
  "password": "password"
}

###

GET {{AspNetCoreEcommerce_HostAddress}}/api/product/

###
POST {{AspNetCoreEcommerce_HostAddress}}/api/cart/add/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJDdXN0b21lciIsImlzcyI6IkFzcE5ldENvcmVXZWJBcGkiLCJleHAiOjE3NDA2NjA5NTksInN1YiI6IjAxOTU0M2I2LTYxNGUtN2Y4My04ZWM5LTc5Mzg4N2UyMzM2MiIsImVtYWlsIjoidXNlcm9uZUBlbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJDdXN0b21lciIsImlhdCI6MTc0MDY1NzM1OSwibmJmIjoxNzQwNjU3MzU5fQ.LevlNs4sieRc6cl455DiuA0AyOH7wxidpnCYjrz-0V0

{
  "productId": "01951487-ed0b-72ac-b7f1-a562259107c8",
  "quantity": 5
}


###
GET {{AspNetCoreEcommerce_HostAddress}}/api/cart/view/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJDdXN0b21lciIsImlzcyI6IkFzcE5ldENvcmVXZWJBcGkiLCJleHAiOjE3NDA2NjA5NTksInN1YiI6IjAxOTU0M2I2LTYxNGUtN2Y4My04ZWM5LTc5Mzg4N2UyMzM2MiIsImVtYWlsIjoidXNlcm9uZUBlbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJDdXN0b21lciIsImlhdCI6MTc0MDY1NzM1OSwibmJmIjoxNzQwNjU3MzU5fQ.LevlNs4sieRc6cl455DiuA0AyOH7wxidpnCYjrz-0V0

###

DELETE {{AspNetCoreEcommerce_HostAddress}}/api/cart/remove/97951466-ed0b-72ac-b7f1-a562259107c8/
Content-Type: /application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJDdXN0b21lciIsImlzcyI6IkFzcE5ldENvcmVXZWJBcGkiLCJleHAiOjE3NDA0MDcwNTEsInN1YiI6IjAxOTUzODFmLWI4MmMtN2Q1Yy1hNjZkLWI4MDM1M2EyMmE0ZCIsImVtYWlsIjoidXNlcm9uZUBlbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJDdXN0b21lciIsImlhdCI6MTc0MDQwMzQ1MSwibmJmIjoxNzQwNDAzNDUxfQ.653Tfhtiu4R2cjtu4NZd0jmB4GBMP4OZN2tdPqKEKlc

###
POST {{AspNetCoreEcommerce_HostAddress}}/api/shippingaddress/add/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJDdXN0b21lciIsImlzcyI6IkFzcE5ldENvcmVXZWJBcGkiLCJleHAiOjE3NDA2MDEzOTIsInN1YiI6IjAxOTU0M2I2LTYxNGUtN2Y4My04ZWM5LTc5Mzg4N2UyMzM2MiIsImVtYWlsIjoidXNlcm9uZUBlbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJDdXN0b21lciIsImlhdCI6MTc0MDU5Nzc5MiwibmJmIjoxNzQwNTk3NzkyfQ.ReUyIGAkZREDx6CZTID_z-VxbMxu4QvouOFx-NJTib8

{
  "firstName": "Amaechi",
  "lastName": "Jude",
  "phone": "0987654321",
  "addressOne": "Ajah",
  "secondAddress": "Lagos",
  "city": "Lagos",
  "state": "Lagos",
  "country": "Nigeria",
  "postalCode": "243891"
}
###
GET  {{AspNetCoreEcommerce_HostAddress}}/api/shippingaddress/view/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJDdXN0b21lciIsImlzcyI6IkFzcE5ldENvcmVXZWJBcGkiLCJleHAiOjE3NDA2NjA5NTksInN1YiI6IjAxOTU0M2I2LTYxNGUtN2Y4My04ZWM5LTc5Mzg4N2UyMzM2MiIsImVtYWlsIjoidXNlcm9uZUBlbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJDdXN0b21lciIsImlhdCI6MTc0MDY1NzM1OSwibmJmIjoxNzQwNjU3MzU5fQ.LevlNs4sieRc6cl455DiuA0AyOH7wxidpnCYjrz-0V0


###
POST {{AspNetCoreEcommerce_HostAddress}}/api/order/create/019543ba-c63c-7f15-8e2c-cb3839e060e6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJDdXN0b21lciIsImlzcyI6IkFzcE5ldENvcmVXZWJBcGkiLCJleHAiOjE3NDA2NjA5NTksInN1YiI6IjAxOTU0M2I2LTYxNGUtN2Y4My04ZWM5LTc5Mzg4N2UyMzM2MiIsImVtYWlsIjoidXNlcm9uZUBlbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJDdXN0b21lciIsImlhdCI6MTc0MDY1NzM1OSwibmJmIjoxNzQwNjU3MzU5fQ.LevlNs4sieRc6cl455DiuA0AyOH7wxidpnCYjrz-0V0

###

GET  {{AspNetCoreEcommerce_HostAddress}}/api/order/all/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJDdXN0b21lciIsImlzcyI6IkFzcE5ldENvcmVXZWJBcGkiLCJleHAiOjE3NDEwMTkyNzEsInN1YiI6IjAxOTU0M2I2LTYxNGUtN2Y4My04ZWM5LTc5Mzg4N2UyMzM2MiIsImVtYWlsIjoidXNlcm9uZUBlbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJDdXN0b21lciIsImlhdCI6MTc0MTAxNTY3MSwibmJmIjoxNzQxMDE1NjcxfQ.g1_k6mjpvKq2RGwgj9xMlJwpgq7DJPE6mc_UTfS_sdw

###


POST {{AspNetCoreEcommerce_HostAddress}}/api/payment/initiate/0195442b-7189-74b9-9b0c-3bdcd5460a70/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJDdXN0b21lciIsImlzcyI6IkFzcE5ldENvcmVXZWJBcGkiLCJleHAiOjE3NDEwMTkyNzEsInN1YiI6IjAxOTU0M2I2LTYxNGUtN2Y4My04ZWM5LTc5Mzg4N2UyMzM2MiIsImVtYWlsIjoidXNlcm9uZUBlbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJDdXN0b21lciIsImlhdCI6MTc0MTAxNTY3MSwibmJmIjoxNzQxMDE1NjcxfQ.g1_k6mjpvKq2RGwgj9xMlJwpgq7DJPE6mc_UTfS_sdw

###